apiVersion: charts.helm.k8s.io/v1alpha1
kind: AiMlWorkshopChart
metadata:
  name: example-aimlworkshopchart
spec:
  # Default values copied from <project_dir>/helm-charts/ai-ml-workshop-chart/values.yaml

  affinity: {}
  autoscaling:
    enabled: false
    maxReplicas: 100
    minReplicas: 1
    targetCPUUtilizationPercentage: 80
  fullnameOverride: ""
  image:
    pullPolicy: IfNotPresent
    repository: quay.io/willbenton/ml-workflows-for-developers
    tag: summit2019
  imagePullSecrets: []
  ingress:
    annotations: {}
    enabled: false
    hosts:
    - host: chart-example.local
      paths: []
    tls: []
  nameOverride: ""
  nodeSelector: {}
  podAnnotations: {}
  podSecurityContext: {}
  replicaCount: 1
  resources: {}
  securityContext: {}
  service:
    port: 8888
    type: ClusterIP
  serviceAccount:
    annotations: {}
    create: true
    name: ""
  tolerations: []
