apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-ml-workshop-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ai-ml-workshop-operator
  template:
    metadata:
      labels:
        name: ai-ml-workshop-operator
    spec:
      serviceAccountName: ai-ml-workshop-operator
      containers:
        - name: ai-ml-workshop-operator
          # Replace this with the built image name
          image: quay.io/aaziz/ai-ml-workshop-operator:v0.0.2
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ai-ml-workshop-operator"
