{{- $fullName := include "ai-ml-workshop-chart.fullname" . -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ai-ml
  labels:
    app: ai-ml
    name: ai-ml
spec:
  path: /
  to:
    kind: Service
    name: {{ $fullName }}
