apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-ml-workshop-chart.fullname" . }}
  labels:
    {{- include "ai-ml-workshop-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http-port
  selector:
    {{- include "ai-ml-workshop-chart.selectorLabels" . | nindent 4 }}
